apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-provider-class
  namespace: secret-demo
spec:
  provider: aws
    # secretObjects:
    # - secretName: app.config
    # type: Opaque
    # data:
    # - objectName: app-conf
    #  key: config
  parameters:
    objects: |
      - objectName: myapp-conf
        objectType: secretsmanager
          # objectAlias: app-conf

