apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-provider-class
  namespace: dev
spec:
  provider: aws
  secretObjects:
    - secretName: env
      type: Opaque
      data:
      - objectName: ENV
        key: ENV
    - secretName: envtag
      type: Opaque
      data:
      - objectName: ENV_TAG
        key: ENV_TAG
    - secretName: host
      type: Opaque
      data:
      - objectName: SQL_HOST
        key: SQL_HOST
    - secretName: user
      type: Opaque
      data:
      - objectName: SQL_USER
        key: SQL_USER
    - secretName: albtag
      type: Opaque
      data:
      - objectName: ALB_TAG
        key: ALB_TAG
    - secretName: sqldb
      type: Opaque
      data:
      - objectName: SQL_DB
        key: SQL_DB
    - secretName: sqlpass
      type: Opaque
      data:
      - objectName: SQL_PASSWORD
        key: SQL_PASSWORD
    - secretName: token
      type: Opaque
      data:
      - objectName: VALIDATION_TOKEN_API
        key: VALIDATION_TOKEN_API
    - secretName: mongourl
      type: Opaque
      data:
      - objectName: MONGO_URL
        key: MONGO_URL
  parameters:
    objects: |
      - objectName: "/recommendation/qa/ecs/ENV"
        objectType: "ssmparameter"
        objectAlias: ENV
      - objectName: "/recommendation/qa/ecs/ENV_TAG"
        objectType: "ssmparameter"
        objectAlias: ENV_TAG
      - objectName: "/recommendation/qa/ecs/MONGO_CONFIG_URL"
        objectType: "ssmparameter"
        objectAlias: MONGO_URL
      - objectName: "/recommendation/qa/ecs/SQL_HOST"
        objectType: "ssmparameter"
        objectAlias: SQL_HOST
      - objectName: "/recommendation/qa/ecs/SQL_DB"
        objectType: "ssmparameter"
        objectAlias: SQL_DB
      - objectName: "/recommendation/qa/ecs/SQL_USER"
        objectType: "ssmparameter"
        objectAlias: SQL_USER
      - objectName: "/recommendation/qa/ecs/SQL_PASSWORD"
        objectType: "ssmparameter"
        objectAlias: SQL_PASSWORD
      - objectName: "/recommendation/qa/ecs/VALIDATE_TOKEN_API"
        objectType: "ssmparameter"
        objectAlias: VALIDATION_TOKEN_API
      - objectName: "/recommendation/qa/ecs/ALB_TAG"
        objectType: "ssmparameter"
        objectAlias: ALB_TAG





