apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: webapp
          image: nginx
          ports:
            - containerPort: 80
          env:
            - name: DB_HOSTNAME
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password

---

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: web
spec:
  selector:
      app: web
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30123

