apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}-service2
  namespace: {{.Values.NameSpace}}
  labels:
    app: webapp2
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: {{.Values.Service.Annotation}} #/recommendations-api-qa/
spec:
  type: {{.Values.Service.Type}} #NodePort
  selector:
    app: webapp2
  ports:
    - port: {{.Values.Service.Port}}
      targetPort: {{.Values.Service.TargetPort}}

