apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sp-class
  namespace: secret-demo
spec:
  provider: aws
  secretObjects:
  - secretName: db-creds
    type: Opaque
    data: 
    - objectName: USERNAME
      key: "username"
    - objectName: PASSWORD
      key: "password"
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:ap-south-1:276780518338:secret:DB_secrets-nHMROk"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: USERNAME
          - path: "password"
            objectAlias: PASSWORD

