apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: secret-demo
spec:
  provider: aws
  secretObjects:
  - secretName: db-creds
    type: Opaque
    data: 
    - objectName: secret-token
      key: SECRET_TOKEN
  parameters:
    objects: |
      - objectName: DB_secrets
        objectType: secretsmanager
        objectAlias: secret-token
