apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp2-deployment
  namespace: secret-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp2
  template:
    metadata:
      name: webapp2
      labels:
        app: webapp2
    spec:
      serviceAccountName: demo-sa
      containers:
        - name: recommendations-api-qa
          image: 276780518338.dkr.ecr.ap-south-1.amazonaws.com/recommendations-service-qa:recommendation-qa-withoutconfig
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp2-service
  labels:
    app: webapp2
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /recommendations-api-qa/docs/
spec:
  type: ClusterIP
  selector:
    app: webapp2
  ports:
    - port: 80
      targetPort: 80
