apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: secret-demo
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: demo-sa
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: mysecret2
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: mysecret2
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "secret-provider-class"
