apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-provider-class
  namespace: secret-demo
spec:
  provider: aws
  secretObjects:
  - secretName: db-secrets
    type: Opaque
    data:
    - objectName: db-secrets
      key: username
  parameters:
    objects: |
      array:
        - |
          objectName: "demo-parameter"
          objectType: "ssmparameter"
        - |
          objectName: "DB_secrets"
          objectType: "secretsmanager"
