apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-provider-class
  namespace: secret-demo
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "app-conf"
        objectType: "secretsmanager"
