apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-qa-deployment
  namespace: secret-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      # initContainers:
      #  - name: db-check
      #    image: busybox:1.31
      #    command: ["sleep","3000"]
      serviceAccountName: demo-sa
      volumes:
        - name: app-conf
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: secret-provider-class
      containers:
        - name: webapp
          image: 276780518338.dkr.ecr.ap-south-1.amazonaws.com/recommendations-service-qa:recommendation-qa-withoutconfig
          imagePullPolicy: Always
          volumeMounts:
          - name: app-conf
            mountPath: /mnt/app/conf
            readOnly: true
      imagePullSecrets:
      - name: repo-cred
            #env:
            #- name: DB_HOST
            #  value: "mysql"
            #- name: DB_PORT
            #  value: "3306"
            #- name: DB_USERNAME
            #  value: "root"
            #- name: DB_NAME
            #  value: "db1"
            #- name: DB_PASSWORD
            #  valueFrom:
            #    secretKeyRef:
            #      name: rds-db-pass
            #      key: password
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: secret-demo
  labels:
    app: webapp
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
    - port: 80
      targetPort: 80


