apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name}}-deployment1 #recommendations-service-qa-deployment1
  namespace: {{ .Values.NameSpace}} #dev
spec:
  replicas: {{.Values.ReplicaCount}} #1
  selector:
    matchLabels:
      app: webapp1
  template:
    metadata:
      name: webapp1
      labels:
        app: webapp1
    spec:
      serviceAccountName: {{.Values.ServiceAccount.Name}} #dev-sa
      volumes:
        - name: {{.Values.Volume.Name}}
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{.Values.SecretProvider.ClassName}} #secret-provider-class
      containers:
        - name: {{.Chart.Name}} #
          image: {{.Values.Image.RepositoryName}}:{{.Values.Image.Tag}} #276780518338.dkr.ecr.ap-south-1.amazonaws.com/recommendations-service-qa:recommendation-qa-withoutconfig
          imagePullPolicy: {{.Values.Image.PullPolicy}}
          ports:
            - containerPort: {{.Values.Container.Port}}
          volumeMounts:
            - name: {{.Values.Volume.Name}}
              mountPath: {{.Values.Volume.MountPath}}
              readOnly: true
          env:
            - name: ENV
              valueFrom:
                secretKeyRef:
                  name: env
                  key: ENV
            - name: ENV_TAG
              valueFrom:
                secretKeyRef:
                  name: envtag
                  key: ENV_TAG
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: mongourl
                  key: MONGO_URL
            - name: SQL_HOST
              valueFrom:
                secretKeyRef:
                  name: host
                  key: SQL_HOST
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqlpass
                  key: SQL_PASSWORD
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: user
                  key: SQL_USER
            - name: SQL_DB
              valueFrom:
                secretKeyRef:
                  name: sqldb
                  key: SQL_DB
            - name: VALIDATION_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: token
                  key: VALIDATION_API_TOKEN
          
