apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{.Values.SecretProvider.ClassName}} #secret-provider-class
  namespace: {{.Values.NameSpace}} #dev
spec:
  provider: {{.Values.SecretProvider.Name}}
  secretObjects:
    - secretName: env
      type: Opaque
      data:
      - objectName: env
        key: ENV
    - secretName: envtag
      type: Opaque
      data:
      - objectName: envtag
        key: ENV_TAG
    - secretName: host
      type: Opaque
      data:
      - objectName: sqlhost
        key: SQL_HOST
    - secretName: user
      type: Opaque
      data:
      - objectName: sqluser
        key: SQL_USER
    - secretName: sqldb
      type: Opaque
      data:
      - objectName: sqldb
        key: SQL_DB
    - secretName: sqlpass
      type: Opaque
      data:
      - objectName: sqlpass
        key: SQL_PASSWORD
    - secretName: token
      type: Opaque
      data:
      - objectName: validationapitoken
        key: VALIDATION_API_TOKEN
    - secretName: mongourl
      type: Opaque
      data:
      - objectName: mongourl
        key: MONGO_URL
  parameters:
    objects: |
      - objectName: {{.Values.SecretProvider.Object1.Name}} #"/recommendation/qa/ecs/ENV"
        objectType: {{.Values.SecretProvider.Type2}}
        objectAlias: env
      - objectName: {{.Values.SecretProvider.Object2.Name}} 
        objectType: {{.Values.SecretProvider.Type2}}
        objectAlias: envtag
      - objectName: {{.Values.SecretProvider.Object3.Name}} 
        objectType: {{.Values.SecretProvider.Type2}}
        objectAlias: mongourl
      - objectName: {{.Values.SecretProvider.Object4.Name}} 
        objectType: {{.Values.SecretProvider.Type2}}
        objectAlias: sqlhost
      - objectName: {{.Values.SecretProvider.Object5.Name}} 
        objectType: {{.Values.SecretProvider.Type2}}
        objectAlias: sqldb
      - objectName: {{.Values.SecretProvider.Object6.Name}} 
        objectType: {{.Values.SecretProvider.Type2}}
        objectAlias: sqluser
      - objectName: {{.Values.SecretProvider.Object7.Name}} 
        objectType: {{.Values.SecretProvider.Type2}}
        objectAlias: sqlpass
      - objectName: {{.Values.SecretProvider.Object8.Name}} 
        objectType: {{.Values.SecretProvider.Type2}}
        objectAlias:  validationapitoken





