apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sp3-class
  namespace: secret-demo
spec:
  provider: aws
  secretObjects:
  - secretName: app-conf
    type: Opaque
    data:
    - objectName: app-conf
      key: env-conf

  parameters:
    objects: |
      - objectName: appconf
        objectType: ssmparameter
        objectAlias: app-conf

