apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: secret-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: demo-sa
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: my-aws-secrets
          mountPath: /mnt/db/creds
          readOnly: true
      volumes:
      - name: my-aws-secrets
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: sp-class
