apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sp-class
  namespace: secret-demo
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "DB_secrets"
        objectType: "secretsmanager"

